apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vcenteremu
  labels:
    app.kubernetes.io/name: vcenteremu
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: vcenteremu
  labels:
    app.kubernetes.io/name: vcenteremu
spec:
  output:
    to:
      kind: ImageStreamTag
      name: vcenteremu:latest
  source:
    type: Git
    git:
      uri: https://github.com/alfbach/vcenteremu.git
      ref: main
    contextDir: /
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
    - type: ConfigChange
    - type: ImageChange
