apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vcenteremu-uploads
  labels:
    app.kubernetes.io/name: vcenteremu
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
